// Code generated by foggo; DO NOT EDIT.

package examples

type ImageOption interface {
	apply(*Image)
}

type WidthOption struct {
	Width int
}

func (o WidthOption) apply(s *Image) {
	s.Width = o.Width
}

type HeightOption struct {
	Height int
}

func (o HeightOption) apply(s *Image) {
	s.Height = o.Height
}

type AltOption struct {
	Alt string
}

func (o AltOption) apply(s *Image) {
	s.Alt = o.Alt
}

func NewImage(options ...ImageOption) *Image {
	s := &Image{}

	for _, option := range options {
		option.apply(s)
	}

	return s
}
